apiVersion: v1
kind: Service
metadata:
  name: snapresize-backend-service
spec:
  type: NodePort
  selector:
    app: snapresize-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30005  # Accessible externally on http://localhost:30005